name: A101 Email Watcher (5 min)

on:
  schedule:
    - cron: "*/5 * * * *"   # every 5 minutes (UTC)
  workflow_dispatch: {}

jobs:
  check:
    runs-on: ubuntu-latest
    # Use Microsoft's Playwright image (browsers + deps preinstalled)
    container:
      image: mcr.microsoft.com/playwright/python:v1.46.1-jammy

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      # sanity check: make sure your script is in the repo root
      - name: Show repo contents
        run: |
          pwd
          ls -la
          test -f watch_a101_email.py || (echo "watch_a101_email.py missing" && exit 1)

      - name: Run watcher
        env:
          A101_URL: https://www.a101.com.tr/liste/a101-ekstra-apple
          SEARCH_TEXT: Apple 
          SMTP_HOST: ${{ secrets.SMTPHOST }}
          SMTP_PORT: ${{ secrets.SMTPPORT }}
          SMTP_USER: ${{ secrets.SMTPUSER }}
          SMTP_PASS: ${{ secrets.SMTPPASS }}
          FROM_EMAIL: ${{ secrets.FROMEMAIL }}
          TO_EMAIL: ${{ secrets.TOEMAIL }}
          HEADLESS: "1"
        run: python watch_a101_email.py

      - name: Upload artifacts (HTML + screenshot)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: a101-debug
          path: artifacts/
          if-no-files-found: ignore
