name: A101 Email Watcher (5 min)

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch: {}

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Show repo contents
        run: |
          pwd
          ls -la
          test -f watch_a101_email.py || (echo "watch_a101_email.py missing" && exit 1)

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install playwright

      - name: Install Playwright browsers (with deps)
        run: |
          python -m playwright install --with-deps chromium || python -m playwright install chromium

      - name: Run watcher
        env:
          A101_URL: https://www.a101.com.tr/liste/a101-ekstra-apple
          SEARCH_TEXT: Apple 
          SMTP_HOST: ${{ secrets.SMTPHOST }}
          SMTP_PORT: ${{ secrets.SMTPPORT }}
          SMTP_USER: ${{ secrets.SMTPUSER }}
          SMTP_PASS: ${{ secrets.SMTPPASS }}
          FROM_EMAIL: ${{ secrets.FROMEMAIL }}
          TO_EMAIL: ${{ secrets.TOEMAIL }}
          HEADLESS: "1"
        run: python watch_a101_email.py

      - name: Upload artifacts (HTML + screenshot)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: a101-debug
          path: artifacts/
          if-no-files-found: ignore
