name: A101 Email Watcher (5 min)

on:
  schedule:
    - cron: "*/5 * * * *"   # every 5 minutes (UTC)
  workflow_dispatch: {}      # run manually when you want

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - run: pip install playwright

      # Install browsers + OS deps for Playwright
      - uses: microsoft/playwright-github-action@v1
        with:
          with-deps: true

      - name: Run watcher
        env:
          A101_URL: https://www.a101.com.tr/liste/a101-ekstra-apple
          SEARCH_TEXT: Apple iPhone 17 256 GB Cep
          # Map to the secrets you created (names without underscores)
          SMTP_HOST: ${{ secrets.SMTPHOST }}
          SMTP_PORT: ${{ secrets.SMTPPORT }}
          SMTP_USER: ${{ secrets.SMTPUSER }}
          SMTP_PASS: ${{ secrets.SMTPPASS }}
          FROM_EMAIL: ${{ secrets.FROMEMAIL }}
          TO_EMAIL: ${{ secrets.TOEMAIL }}
          HEADLESS: "1"
        run: python watch_a101_email.py
